import { Roboto_Flex} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
const poppins = Roboto_Flex({
  subsets: ['latin'],
  weight: ['100','200','300','400',"500",'600', '700'], // choose the weights you need
  display: 'swap',     
  
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={` bg-[#171717] antialiased`}
      >
        <NavBar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
